name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos
        uses: Randomblock1/theos-action@v1.4
        with:
          theos-dir: ${{ github.workspace }}/theos
          theos-src: https://github.com/theos/theos
          theos-sdks: https://github.com/theos/sdks
          theos-sdks-branch: master
          orion: false

      - name: Build AutoFLEX
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Show generated packages
        run: |
          echo "Generated files:"
          find packages -type f -maxdepth 3 -print || true

      - name: Upload AutoFLEX artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoFLEX-DEB
          path: packages/**
          if-no-files-found: error
